### ISSUE TITLE
Getting error while running index.bat file

### ISSUE THREAD

**Issue by mgupta0421** [microsoft/lsif-java#79]
**Describe the bug**

Getting the error while running the command for  .index.bat. Please find the screenshot to refer to the problem.
![image](https://user-images.githubusercontent.com/44102012/112463798-fadc8700-8d62-11eb-993e-290b796fd2de.png)

**Comment by jdneo** [comment]
`index.bat` should only be used in Windows terminal.

**Comment by mgupta0421** [comment]
> `index.bat` should only be used in Windows terminal.

I want to create the dump.lsif file for a project in mac terminal, so then which file will be used?

**Comment by jdneo** [comment]
There is no such launch file for mac now. You can interpret the content in index.bat to shell as a workaround.
